// SSDP Discovery Server for Roku devices
// Generated by integration_engineer agent, assembled into running app

const express = require('express');
const dgram = require('dgram');
const http = require('http');
const { XMLParser } = require('fast-xml-parser');

const app = express();
const PORT = 3001;
const SSDP_IP = '239.255.255.250';
const SSDP_PORT = 1900;
const SEARCH_TARGET = 'roku:ecp';

let discoveredDevices = [];

// ─── SSDP M-SEARCH ─────────────────────────────────────────────────────────

function discoverRoku() {
  return new Promise((resolve) => {
    const socket = dgram.createSocket({ type: 'udp4', reuseAddr: true });
    const found = new Map();

    const message = Buffer.from(
      'M-SEARCH * HTTP/1.1\r\n' +
      `HOST: ${SSDP_IP}:${SSDP_PORT}\r\n` +
      'MAN: "ssdp:discover"\r\n' +
      `ST: ${SEARCH_TARGET}\r\n` +
      'MX: 3\r\n' +
      '\r\n'
    );

    socket.on('message', (msg) => {
      const text = msg.toString();
      const locationMatch = text.match(/LOCATION:\s*(.*)/i);
      if (locationMatch && text.toLowerCase().includes('roku')) {
        const location = locationMatch[1].trim();
        if (!found.has(location)) {
          found.set(location, { location, discoveredAt: new Date().toISOString() });
        }
      }
    });

    socket.on('error', (err) => {
      console.error('SSDP error:', err.message);
      socket.close();
      resolve([]);
    });

    socket.bind(() => {
      try {
        socket.addMembership(SSDP_IP);
        socket.send(message, 0, message.length, SSDP_PORT, SSDP_IP);
      } catch (e) {
        console.error('SSDP send error:', e.message);
      }
    });

    setTimeout(() => {
      socket.close();
      resolve(Array.from(found.values()));
    }, 4000);
  });
}

// ─── Fetch Device Info XML ──────────────────────────────────────────────────

function fetchDeviceInfo(locationUrl) {
  return new Promise((resolve) => {
    const url = new URL(locationUrl);
    const infoUrl = `http://${url.hostname}:${url.port || 8060}/query/device-info`;

    http.get(infoUrl, { timeout: 5000 }, (res) => {
      let data = '';
      res.on('data', (chunk) => data += chunk);
      res.on('end', () => {
        try {
          const parser = new XMLParser();
          const parsed = parser.parse(data);
          const info = parsed['device-info'] || {};
          resolve({
            ip: url.hostname,
            port: url.port || '8060',
            name: info['friendly-device-name'] || info['user-device-name'] || 'Roku',
            model: info['model-name'] || 'Unknown',
            serial: info['serial-number'] || '',
            software: info['software-version'] || '',
            location: locationUrl
          });
        } catch {
          resolve({ ip: url.hostname, port: url.port || '8060', name: 'Roku', model: 'Unknown', location: locationUrl });
        }
      });
    }).on('error', () => {
      const url2 = new URL(locationUrl);
      resolve({ ip: url2.hostname, port: url2.port || '8060', name: 'Roku (unreachable)', model: 'Unknown', location: locationUrl });
    });
  });
}

// ─── Discovery Loop ─────────────────────────────────────────────────────────

async function runDiscovery() {
  console.log('[Discovery] Scanning for Roku devices...');
  const raw = await discoverRoku();
  const devices = [];
  for (const entry of raw) {
    const info = await fetchDeviceInfo(entry.location);
    devices.push(info);
  }
  discoveredDevices = devices;
  console.log(`[Discovery] Found ${devices.length} device(s):`, devices.map(d => `${d.name} (${d.ip})`).join(', ') || 'none');
}

// Run immediately, then every 30 seconds
runDiscovery();
setInterval(runDiscovery, 30000);

// ─── REST API ───────────────────────────────────────────────────────────────

app.use((req, res, next) => {
  res.header('Access-Control-Allow-Origin', '*');
  next();
});

app.get('/api/devices', (req, res) => {
  res.json(discoveredDevices);
});

app.get('/api/discover', async (req, res) => {
  await runDiscovery();
  res.json(discoveredDevices);
});

app.listen(PORT, () => {
  console.log(`[Discovery] Server running on http://localhost:${PORT}`);
  console.log(`[Discovery] GET /api/devices — list discovered Rokus`);
  console.log(`[Discovery] GET /api/discover — force re-scan`);
});
